AllCops:
  Exclude:
    - 'gemfiles/**/*'
    - 'vendor/**/*'
    - 'lib/generators/*/notifier/templates/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable

Layout/LineLength:
  Exclude:
    - 'outbox-rails.gemspec'
  IgnoreCopDirectives: true
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Naming/FileName:
  Exclude:
    - 'Appraisals'
    - 'lib/outbox-rails.rb'

Style/Documentation:
  Enabled: false
