AllCops:
  Exclude:
    - 'gemfiles/**/*'
    - 'vendor/**/*'
    - 'lib/generators/*/notifier/templates/*'
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Exclude:
    - 'outbox-rails.gemspec'
  IgnoreCopDirectives: true
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'Appraisals'
