sudo: false
cache: bundler
language: ruby
rvm:
  - 2.6.6
  - 2.7.1
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
before_install:
  - gem install bundler:2.1.4
script:
  - bundle exec rubocop
  - bundle exec rspec
