sudo: false
cache: bundler
language: ruby
rvm:
  - 2.6.6
  - 2.7.1
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
script:
  - bundle exec rubocop
  - bundle exec rspec
